DROP TABLE IF EXISTS "InstitutionalProfile" CASCADE;
CREATE TABLE "InstitutionalProfile" (
    "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    "userId" TEXT NOT NULL UNIQUE REFERENCES "User"("id") ON DELETE CASCADE,
    "institutionName" TEXT NOT NULL,
    "institutionType" TEXT NOT NULL,
    "country" TEXT,
    "state" TEXT,
    "website" TEXT,
    "officialEmailDomain" TEXT,
    "description" TEXT,
    "logoUrl" TEXT,
    "bannerUrl" TEXT,
    "repFullName" TEXT,
    "repJobTitle" TEXT,
    "repDepartment" TEXT,
    "repOfficialEmail" TEXT,
    "repPhone" TEXT,
    "repIdUrl" TEXT,
    "repLinkedInUrl" TEXT,
    "repAuthLetterUrl" TEXT,
    "twoFactorEnabled" BOOLEAN DEFAULT false,
    "primaryRole" TEXT DEFAULT 'publisher',
    "recoveryEmail" TEXT,
    "recoveryPhone" TEXT,
    "isVerified" BOOLEAN DEFAULT false,
    "isDomainVerified" BOOLEAN DEFAULT false,
    "supportingDocs" JSONB,
    "transparencyAccepted" BOOLEAN DEFAULT false,
    "termsAccepted" BOOLEAN DEFAULT false,
    "publicDisplayName" TEXT,
    "publicBio" TEXT,
    "headquarters" TEXT,
    "categories" JSONB,
    "languages" JSONB,
    "status" TEXT DEFAULT 'pending',
    "adminNotes" TEXT,
    "badgeType" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
